### ISSUE TITLE
DevOps (Nginx, Linux, VM, instance setup)

### ISSUE THREAD

**Issue by EmilioLilie** [coderbunker/demoZuerich#10]

**Comment by maroxas** [comment]
Nginx README.md file is already uploaded in /demoZuerich/nginx/
There is no source code file of Nginx because I don't need to configure anything.

**Comment by Sheryl-Chelagat** [comment]
Instance is running (Ubuntu). For proof, check YouTube videos... https://www.youtube.com/watch?v=jRs8cSemStI&list=PLhVLYZA4y4CZ-37uF35Rih01o-AwpLXgD&index=4
