### ISSUE TITLE
a series of link in order to the necessary documentation to setup a whole system quickly after checking out this source code.

### ISSUE THREAD

**Issue by EmilioLilie** [coderbunker/demoZuerich#18]

**Comment by EmilioLilie** [comment]
To get the arduino up and running you should be able to follow the instructions in the README.md.
For further infomation on the programming language you can visit https://www.arduino.cc/en/Reference/HomePage
For more information about the electronics https://learn.sparkfun.com/tutorials is a useful page

**Comment by Sheryl-Chelagat** [comment]
The list of links was updaten in the ReadeMe.

**Comment by Sheryl-Chelagat** [comment]
* The list of the links was updated in the readme
