### ISSUE TITLE
Sensor (Arduino microcontroller)

### ISSUE THREAD

**Issue by EmilioLilie** [coderbunker/demoZuerich#5]

**Comment by EmilioLilie** [comment]
Updatet the code and the README.md

**Comment by rngadam** [comment]
* Description should detail what the expectation / requirements was
* Image diagram for the Arduino schematic should be part of the repo and embedded into the README.md
* There's no indication or documentation of how the calculation for temperature is done and what exact electronic component we're using (should link to the datasheet?)

**Comment by EmilioLilie** [comment]
Updatet the Readme
