### ISSUE TITLE
Database (PostgreSQL)

### ISSUE THREAD

**Issue by EmilioLilie** [coderbunker/demoZuerich#7]

**Comment by alessandropugliese** [comment]
Successful connection with postgraphql. Created dump, uploaded on github/demoZuerich/PostgreSQL. 
YouTube Video: https://www.youtube.com/watch?v=1h9RwElXkaA&list=PLhVLYZA4y4CZ-37uF35Rih01o-AwpLXgD (neighbours graphql/postgresql). Readme.md updated with more content. New schema and new tables created with varchar datatype.
